"""Add auto-generated IDs, ParentStudent relations, and SchoolConfig

Revision ID: 03bdded6f550
Revises: 70ab7cf51234
Create Date: 2026-03-01 07:13:01.729089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bdded6f550'
down_revision: Union[str, Sequence[str], None] = '70ab7cf51234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'guardian_contact')
    op.drop_column('students', 'guardian_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('guardian_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('guardian_contact', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
