"""Add SchoolLevel table and Class ALevelCategory

Revision ID: 3a71c68460a9
Revises: aacfaa282869
Create Date: 2026-03-05 07:17:51.047905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3a71c68460a9'
down_revision: Union[str, Sequence[str], None] = 'aacfaa282869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create the school_levels table 
    # ✅ FIX: Tell Postgres NOT to create the ENUM again using create_type=False
    op.create_table('school_levels',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('level', postgresql.ENUM('NURSERY', 'PRIMARY', 'O_LEVEL', 'A_LEVEL', name='academiclevel', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'level', name='_school_academic_level_uc')
    )
    op.create_index(op.f('ix_school_levels_school_id'), 'school_levels', ['school_id'], unique=False)
    
    # 2. MANUALLY CREATE THE ENUM TYPE IN POSTGRES BEFORE ADDING THE COLUMN
    alevel_category_enum = postgresql.ENUM('SCIENCES', 'ARTS', name='alevelcategory')
    alevel_category_enum.create(op.get_bind())
    
    # 3. Now it is safe to add the column
    op.add_column('classes', sa.Column('category', alevel_category_enum, nullable=True))
    
    # 4. Handle the constraints
    op.drop_constraint('_school_class_stream_uc', 'classes', type_='unique')
    op.create_unique_constraint('_school_class_stream_category_uc', 'classes', ['school_id', 'name', 'stream', 'category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_school_class_stream_category_uc', 'classes', type_='unique')
    op.create_unique_constraint('_school_class_stream_uc', 'classes', ['school_id', 'name', 'stream'])
    op.drop_column('classes', 'category')
    
    # MANUALLY DROP THE ENUM TYPE FROM POSTGRES
    alevel_category_enum = postgresql.ENUM('SCIENCES', 'ARTS', name='alevelcategory')
    alevel_category_enum.drop(op.get_bind())
    
    op.drop_index(op.f('ix_school_levels_school_id'), table_name='school_levels')
    op.drop_table('school_levels')
    # ### end Alembic commands ###