"""link_school_to_settings

Revision ID: 70ab7cf51234
Revises: b7621a4a0538
Create Date: 2026-02-28 15:31:41.288379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ab7cf51234'
down_revision: Union[str, Sequence[str], None] = 'b7621a4a0538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_configurations',
    sa.Column('current_academic_year', sa.Integer(), nullable=False),
    sa.Column('current_term', sa.Integer(), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_configurations_school_id'), 'school_configurations', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_configurations_school_id'), table_name='school_configurations')
    op.drop_table('school_configurations')
    # ### end Alembic commands ###
