"""add_form_teacher_to_classes

Revision ID: af417a6695b1
Revises: 75df4b46c34a
Create Date: 2026-02-28 09:14:11.910180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af417a6695b1'
down_revision: Union[str, Sequence[str], None] = '75df4b46c34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('form_teacher_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_classes_form_teacher_id'), 'classes', ['form_teacher_id'], unique=False)
    op.create_foreign_key(None, 'classes', 'teachers', ['form_teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index(op.f('ix_classes_form_teacher_id'), table_name='classes')
    op.drop_column('classes', 'form_teacher_id')
    # ### end Alembic commands ###
