"""add_teacher_assignments_and_soft_deletes

Revision ID: c04f3a0c73bc
Revises: aea022d98507
Create Date: 2026-02-25 06:25:31.809225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04f3a0c73bc'
down_revision: Union[str, Sequence[str], None] = 'aea022d98507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_assignments',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'class_id', name='_teacher_subject_class_uc')
    )
    op.create_index(op.f('ix_teacher_assignments_class_id'), 'teacher_assignments', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_school_id'), 'teacher_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_subject_id'), 'teacher_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    op.drop_constraint(op.f('fee_payments_student_id_fkey'), 'fee_payments', type_='foreignkey')
    op.drop_constraint(op.f('fee_payments_fee_structure_id_fkey'), 'fee_payments', type_='foreignkey')
    op.create_foreign_key(None, 'fee_payments', 'students', ['student_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'fee_payments', 'fee_structures', ['fee_structure_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fee_structures_class_id_fkey'), 'fee_structures', type_='foreignkey')
    op.create_foreign_key(None, 'fee_structures', 'classes', ['class_id'], ['id'], ondelete='RESTRICT')
    op.add_column('schools', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'deleted_at')
    op.drop_constraint(None, 'fee_structures', type_='foreignkey')
    op.create_foreign_key(op.f('fee_structures_class_id_fkey'), 'fee_structures', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'fee_payments', type_='foreignkey')
    op.drop_constraint(None, 'fee_payments', type_='foreignkey')
    op.create_foreign_key(op.f('fee_payments_fee_structure_id_fkey'), 'fee_payments', 'fee_structures', ['fee_structure_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fee_payments_student_id_fkey'), 'fee_payments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_subject_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_school_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_class_id'), table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    # ### end Alembic commands ###
